import Head from "next/head"
import { AiFillFacebook, AiFillLinkedin, AiFillGithub } from "react-icons/ai"
import deved from "../public/dev-ed-wave.png"
import deved1 from "../public/saidev_.png"
import Image from "next/image"
import Work from "../components/Work"
import { Canvas } from "react-three-fiber"
import { OrbitControls, Sphere, MeshDistortMaterial } from "@react-three/drei"
import ServicesSection from "../components/ServiceSection"
import About from "../components/About"

export default function Home({ darkMode }) {
  const backgroundImage = darkMode ? deved : deved1;
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Sai Resume</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40'>
        <section className='min-h-screen'>
          <div className='text-center p-10 '>
            <h2 className='text-5xl pb-2 text-teal-600 font-semibold dark:text-teal-400 md:text-6xl'>
              Anindow Saikat
            </h2>
            <h3 className='text-2xl py-2 dark:text-white md:text-3xl'>
              Developer and designer.
            </h3>
            <p className='text-md py-5  leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl'></p>
            <div className='text-5xl flex justify-center gap-16 pt-3 text-gray-600 dark:text-gray-400 group relative cursor-pointer mb-10'>
              <a href='https://www.facebook.com/AnindowS'>
                <AiFillFacebook className='hover:text-teal-600 dark:text-teal-400' />
              </a>

              <a href='https://www.linkedin.com/in/anindow-saikat-20044425b/'>
                <AiFillLinkedin className='hover:text-teal-600 dark:text-teal-400' />
              </a>
              <a href='https://github.com/Anindow/'>
                <AiFillGithub className='hover:text-teal-600 dark:text-teal-400' />
              </a>
              <div className='absolute top-0 -inset-full h-full w-1/2 z-5  block transform -skew-x-12 bg-gradient-to-r from-transparent to-white dark:to-slate-900 opacity-40 group-hover:animate-shine' />
            </div>
            <div className='h-screen flex items-center justify-center -mt-32'>
              <div className='h-96 w-96 hidden sm:block'>
                <Canvas className='ml-16 -mt-40'>
                  <OrbitControls enableZoom={false} />
                  <ambientLight intensity={1} />
                  <directionalLight position={[3, 2, 1]} />
                  <Sphere args={[1, 100, 200]} scale={2.52}>
                    <MeshDistortMaterial
                      color={"#00897B"}
                      distort={0.5}
                      speed={2}
                    />
                  </Sphere>
                </Canvas>
              </div>
              <div className='relative -mt-80 -ml-72 rounded-full  overflow-hidden hidden sm:block'>
                <div className='w-full h-full opacity-80 dark:opacity-100 absolute bg-gradient-to-b from-black to-black' />
                <Image
                  src={backgroundImage}
                  width={300}
                  height={300}
                  className='rounded-full hover:opacity-80 duration-500 hover:rotate-3 hover:scale-125 cursor-none'
                  alt='deved'
                />
                
              </div>
              <div className='sm:hidden -mt-80 '>
                <Image
                  src={deved1}
                  width={300}
                  height={300}
                  className='mx-auto rounded-full'
                  alt='deved'
                />
              </div>
            </div>
          </div>
        </section>
        <ServicesSection />
        <section className='py-10'>
          <div>
            <h3 className='text-3xl lg:text-5xl py-1 dark:text-white'>Portfolio</h3>
            <p className='text-md lg:text-lg py-2 leading-8 text-gray-800 dark:text-gray-200'>
              Independent and self-motivated graduate with a strong enthusiasm
              for creating innovative web solutions. Proficient in utilizing a
              diverse tech stack, including{" "}
              <span className='text-teal-500 font-semibold'>React</span>, Next.js, Node.js,
              Bootstrap, and <span className='text-teal-500 font-semibold'>Tailwind CSS</span>
              . With a solid foundation in front-end development, I have a keen
              eye for detail and a passion for crafting visually appealing and
              user-friendly websites. My expertise extends to back-end
              technologies, allowing me to build robust server-side
              functionalities and APIs using Node.js. I am committed to staying
              updated with the latest trends and best practices in web
              development, ensuring that my projects are at the forefront of
              innovation. With excellent problem-solving skills and a drive for
              continuous learning.
            </p>
          </div>
          <br /> <br /> <br />
          <Work />
          <br /> <br /> <br />
          <About />
        </section>
      </main>
    </div>
  )
}
